import './terms.css';

export const metadata = {
  title: 'Terms of Use',
  alternates: { canonical: '/terms' },
  description: 'The terms governing use of the SSC Control Pvt Ltd website.',
};

export default function TermsPage() {
  return (
    <main className="page-terms">
      <div className="page-hero">
        <div className="hero-tag">Legal</div>
        <h1>Terms of Use</h1>
        <p className="hero-updated">Last updated: April 2025</p>
      </div>

      <div className="terms-content">

        <section>
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using the website <strong>ssccontrol.com</strong> (the
            &ldquo;Site&rdquo;), you agree to be bound by these Terms of Use (&ldquo;Terms&rdquo;).
            If you do not agree with any part of these Terms, please do not use the Site.
          </p>
          <p>
            These Terms apply to all visitors, users, and others who access or use the Site.
            SSC Control Pvt Ltd (&ldquo;SSC Control&rdquo;, &ldquo;we&rdquo;, &ldquo;our&rdquo;,
            or &ldquo;us&rdquo;) reserves the right to modify these Terms at any time. Continued
            use of the Site following the posting of changes constitutes your acceptance of the
            revised Terms.
          </p>
        </section>

        <section>
          <h2>2. Use of the Website</h2>
          <p>
            You may use the Site for lawful purposes only, in accordance with these Terms and all
            applicable laws and regulations. Specifically, you agree that you will not:
          </p>
          <ul>
            <li>
              Use the Site in any manner that could disable, overburden, damage, or impair it,
              or interfere with any other party&rsquo;s use of the Site.
            </li>
            <li>
              Scrape, crawl, spider, harvest, or otherwise extract data from the Site by automated
              means without our prior written consent.
            </li>
            <li>
              Use any robot, bot, script, or other automated device, process, or means to access
              the Site for any purpose, including monitoring or copying any of its content.
            </li>
            <li>
              Attempt to gain unauthorised access to any part of the Site, its servers, or any
              systems connected to the Site.
            </li>
            <li>
              Transmit any unsolicited or unauthorised advertising or promotional material, or
              any other form of solicitation.
            </li>
            <li>
              Use the Site in any way that violates any applicable local, national, or international
              law or regulation.
            </li>
          </ul>
          <p>
            We reserve the right to terminate or restrict your access to the Site at our sole
            discretion, without notice, for conduct that we believe violates these Terms or is
            harmful to other users, us, or third parties.
          </p>
        </section>

        <section>
          <h2>3. Product &amp; Technical Information Disclaimer</h2>
          <p>
            The product data, technical specifications, datasheets, and output generated by any
            selection or sizing tools available on the Site (including motor-starter, VFD, and
            panel-AC tools) are provided for general informational and preliminary guidance
            purposes only.
          </p>
          <p>
            All such information is <strong>indicative</strong>. Specifications are subject to
            change without notice by the respective manufacturers. Results produced by selection
            tools are based on the parameters you enter and general engineering assumptions; they
            do not constitute a formal technical recommendation or a guaranteed bill of materials.
          </p>
          <p>
            <strong>
              You must confirm all product selections, specifications, and suitability with our
              technical team before placing any order or relying on such information for design,
              procurement, or installation decisions.
            </strong>{' '}
            SSC Control accepts no liability for errors, omissions, or outcomes arising from
            reliance on unconfirmed information presented on the Site.
          </p>
        </section>

        <section>
          <h2>4. Intellectual Property</h2>
          <p>
            Unless otherwise indicated, all content on the Site, including but not limited to
            text, graphics, logos, icons, images, page layouts, and software, is the property
            of SSC Control Pvt Ltd and is protected by applicable Indian and international
            intellectual property laws. You may not reproduce, distribute, modify, or create
            derivative works of any Site content without our prior written permission.
          </p>
          <p>
            All third-party brand names, product names, logos, and trademarks referenced on this
            Site, including but not limited to ABB, Mitsubishi Electric, Schmersal, Lovato
            Electric, and Axelon, are the property of their respective owners. Their appearance
            on this Site does not imply any endorsement by or affiliation with SSC Control beyond
            the fact that SSC Control is an authorised channel partner and/or distributor of
            those brands in the regions in which it operates.
          </p>
          <p>
            Any use of third-party marks without the prior written consent of the respective
            trademark owner is strictly prohibited.
          </p>
        </section>

        <section>
          <h2>5. Third-Party Links</h2>
          <p>
            The Site may contain links to third-party websites or services that are not owned or
            controlled by SSC Control. We have no control over, and assume no responsibility for,
            the content, privacy policies, or practices of any third-party sites or services.
          </p>
          <p>
            We encourage you to review the terms and privacy policies of any third-party sites
            you visit. The inclusion of a link on the Site does not imply our endorsement of that
            site or its content.
          </p>
        </section>

        <section>
          <h2>6. Limitation of Liability</h2>
          <p>
            To the fullest extent permitted by applicable law, SSC Control Pvt Ltd, its directors,
            officers, employees, agents, and suppliers shall not be liable for any indirect,
            incidental, special, consequential, or punitive damages, including loss of profits,
            data, goodwill, or other intangible losses, arising out of or in connection with:
          </p>
          <ul>
            <li>Your access to or use of (or inability to use) the Site;</li>
            <li>
              Any reliance placed on the accuracy or completeness of information presented on
              the Site;
            </li>
            <li>
              Unauthorised access to or alteration of your transmissions or data;
            </li>
            <li>
              Any other matter relating to the Site.
            </li>
          </ul>
          <p>
            In no event shall our total cumulative liability to you for all claims arising from
            or relating to your use of the Site exceed the greater of INR&nbsp;1,000 or the
            amount you paid to us in the three months preceding the event giving rise to the
            claim, if any.
          </p>
          <p>
            Some jurisdictions do not allow the exclusion of certain warranties or the limitation
            of liability for certain types of damages. In such jurisdictions, our liability will
            be limited to the maximum extent permitted by law.
          </p>
        </section>

        <section>
          <h2>7. Indemnity</h2>
          <p>
            You agree to defend, indemnify, and hold harmless SSC Control Pvt Ltd and its
            directors, officers, employees, agents, and suppliers from and against any claims,
            liabilities, damages, judgements, awards, losses, costs, and expenses (including
            reasonable legal fees) arising out of or relating to:
          </p>
          <ul>
            <li>Your violation of these Terms;</li>
            <li>Your use or misuse of the Site;</li>
            <li>
              Your infringement of any intellectual property right or other right of any third
              party; or
            </li>
            <li>Any content or data you submit through the Site.</li>
          </ul>
        </section>

        <section>
          <h2>8. Governing Law &amp; Jurisdiction</h2>
          <p>
            These Terms shall be governed by and construed in accordance with the laws of India,
            without regard to its conflict of law principles.
          </p>
          <p>
            Any dispute, controversy, or claim arising out of or relating to these Terms, or the
            breach, termination, or invalidity thereof, shall be subject to the exclusive
            jurisdiction of the courts at Ahmedabad, Gujarat, India. By using the Site, you
            irrevocably consent to the personal jurisdiction of such courts.
          </p>
        </section>

        <section>
          <h2>9. Changes to Terms</h2>
          <p>
            We reserve the right to revise and update these Terms at any time at our sole
            discretion. All changes are effective immediately upon posting and apply to all
            access to and use of the Site thereafter.
          </p>
          <p>
            The &ldquo;Last updated&rdquo; date at the top of this page indicates when the Terms
            were last revised. We encourage you to review these Terms periodically. Your continued
            use of the Site following the posting of revised Terms means that you accept and agree
            to the changes.
          </p>
        </section>

        <section>
          <h2>10. Contact</h2>
          <p>
            If you have any questions about these Terms of Use, please contact us:
          </p>
          <ul>
            <li>
              <strong>Email:</strong>{' '}
              <a href="mailto:sales@ssccontrol.com">sales@ssccontrol.com</a>
            </li>
            <li>
              <strong>Address:</strong> SSC Control Pvt Ltd, E-12, Siddhivinayak Tower,
              S.G. Highway, Makarba, Ahmedabad, Gujarat 380051, India
            </li>
          </ul>
        </section>

      </div>
    </main>
  );
}
